### ISSUE TITLE
Notes functionality

### ISSUE THREAD

**Issue by Karyum** [WebAhead10/webahead-library-frontend#32]
This task is quite big and we are not 100% percent sure how the client wants to implement it, in that case we will start with the basic functionality for it and from there we will pass it to the client and see how to move on from there.

So we need to add notes and a comment section in the view newspaper's sidebar,
> Maybe as a tab, so 1 tab would be the tags and the text, the other tab would be notes and comments
 
it's a place where users can add updates about the newspaper and maybe some extra data.

- [x] Add notes section with some fake comment in the view newpaper sidebar @aziz1980-ctrl 
- [x] Add document_notes table in the database that has the following columns: @tawfeek-eg239
  - id
  - text
  - user_id: _the user who added the note/comment_
  - document_id: _the document that the user has added the comment to_
  - created_at: _the date when the note/comment were added_  @tawfeek-eg239
- [x] Create the controller that adds the note/comment to the db @aziz1980-ctrl 
- [x] Connect with the frontend @aziz1980-ctrl

**Comment by Karyum** [comment]
I assigned @aziz1980-ctrl for the first checkbox **and not the other checkboxes**

**Comment by MahmoudDiab25** [comment]
I assigned @tawfeek-eg239 for the second checkbox and not the other checkboxes

**Comment by aziz1980-ctrl** [comment]
i fixed the request

**Comment by MahmoudDiab25** [comment]
I assigned @tawfeek-eg239 for the last checkbox
